#!/bin/bash

# See documentation for details:
# https://docs.docker.com/docker-hub/builds/advanced/

echo 'Set permissions for persisted data...'
mkdir -p '/srv/dokos/dodock/sites' '/srv/dokos/dodock/logs'
chown "1000:1000" '/srv/dokos/dodock/sites' '/srv/dokos/dodock/logs'
chmod 777 '/srv/dokos/dodock/sites' '/srv/dokos/dodock/logs'
